In [35]:
import numpy as np
import pandas as pd
import random, math
import os
from os import path

In [36]:
def leer_matriz(path_instancia):
    file = open(path_instancia, "r")
    Lines = file.readlines()
    header = [int(Lines[0]), int(Lines[1])]
    Lines = Lines[2:]
    
    relaciones = []
    
    for line in Lines:
        line_data = line.split()
        relaciones.append([int(line_data[0]), int(line_data[1])])
        
    return([header, relaciones])

def leer_resultado(path_instancia):
    file = open(path_instancia, "r")
    Lines = file.readlines()
    
    header = float(Lines[0])
    
    Lines = Lines[1:]
    
    resultados = []
    
    for line in Lines:
        resultados.append(float(line))
        
    return([header, resultados])

In [37]:
def calcular_diferecia_x(archivo_entrada, resultado_entrada, archivo_salida):
    
    salida = open(archivo_salida,'w')
    data = leer_matriz(archivo_entrada)
    header = data[0]
    body = data[1]
    
    M = header[0] # Filas y Columnas de matriz
    N = header[1] # Relaciones
    W = np.zeros((M, M), dtype=float)
    
    for rel in body:
        W[rel[1]-1][rel[0]-1] = 1
        
    D = np.zeros((M, M), dtype=float)
    C = np.zeros(M, dtype=float)
    Z = np.zeros(M, dtype=float)
    E = np.ones(M, dtype=float)
    I = np.identity(M)
    
    for j in range(0, M):
        zeroes = 0
        for i in range(0, M):
            if W[i][j] == 1:
                zeroes = zeroes + 1
        C[j] = zeroes
        
    for i in range(0, M):
        if C[i] != 0:
            D[i][i] = float(1/C[i])
            
    res_current = leer_resultado(resultado_entrada)
    
    p = res_current[0]
    
    for i in range(0, M):
        if C[i] != 0:
            Z[i] = (float((1 - p) / M))
        else:
            Z[i] = (float((1) / M))
    
    Zt = np.transpose(Z)
    A_op = p * np.matmul(W, D)
    Ezt = np.outer(E,Zt)
    A = A_op + Ezt
    x = np.array(res_current[1])
    
    try:
        Ax = np.matmul(A, x)
        # Ax = np.linalg.solve(A, x) # Ax = 0
        
        Ax_x = np.subtract(Ax, x)
        
        print(np.linalg.norm(Ax_x))

        for i in range(0, M):
        #        if Ax_x[i] < float(0):
        #            Ax_x[i] = (-1)*Ax_x[i]
        #            print(Ax_x[i], file=salida)
                                
    except np.linalg.LinAlgError as e:
        if 'Singular matrix' in str(e):
            print("None")
        else:
            raise

In [43]:
def valor_absoluto(archivo_nuestro, archivo_catedra):
    datos_nuestros = leer_resultado(archivo_nuestro)
    datos_catedra = leer_resultado(archivo_catedra)
    
    resta_vectores = np.subtract(datos_nuestros[1], datos_catedra[1])
    
    print(resta_vectores)
    print(np.linalg.norm(resta_vectores))

In [44]:
fnames = []
for root, dirs, files in os.walk("./tests"):
    for file in files:
        if file.endswith(".txt"):
             fnames.append(file.split(".")[0])

fnames = fnames[1:]

for file in fnames:
    if path.exists(F"./tests/{file}.txt") and path.exists(F"./tests/result_nuestro/{file}.txt.out"):
        print(file)
        calcular_diferecia_x(F"./tests/{file}.txt", F"./tests/result_nuestro/{file}.txt.out", F"./tests/{file}.txt.res")
        valor_absoluto(F"./tests/result_nuestro/{file}.txt.out", F"./tests/result_catedra/{file}.txt.out")

test_15_segundos
8.881863243326464e-05
[ 1.585e-06  2.426e-06  2.406e-06 ... -8.400e-07 -2.994e-06 -3.196e-06]
9.295234805813148e-05
test_30_segundos
0.00010465319849105526
[ 1.608e-06  6.130e-07  3.038e-06 ... -3.054e-06 -3.523e-06 -2.981e-06]
0.00010635289396386912
test_aleatorio_desordenado
3.479034349057528e-07
[0. 0. 0. 0. 0.]
0.0
test_completo
5.551115123125783e-17
[0. 0. 0. 0. 0.]
0.0
test_sin_links
6.206335383118183e-17
[0. 0. 0. 0. 0.]
0.0
test_trivial
0.0
[0.]
0.0
